
enum EPhysicsTraceTag
{
    Custom,
    TPCamera,
    LockTargetTrace,
    Kinematic_MoveSweep,
    Kinematic_FindFloor,
    Kinematic_DebugStaticPenetration,
    CheckOverlapping,
    PathFinding,
    HitTest,
    ProjectileGroundMove,
    NATIVE_MAX = 9,
    HandleProjectileHit,
    DivingMove,
    MotionWarping,
    SpawnEcosimGroup,
    EcosimGroupHeightField,
    AIKnowledgePerception,
    CameraOcclusionFade,
    EcosimLevelSpawner,
    HitBoxTest,
    HitPresentation,
    CharacterEnvChecking,
    DropGrounding,
    TestWater,
    GravityFalling,
    LandingPointTest,
    EcosimAIFlyCheck,
    EcosimAIDataCheck,
    BehaviorTreeTask,
    EnvPhysMatTest,
    ViewPortSelectTarget,
    ProjectileTrack,
    GuidingPath,
    EnvSurface,
    LineInteractFx,
    AISimpleMovementGrounding,
    Mark,
    InteractTraceCheck,
    DestructibleTest,
    PropSpawnOnGround,
}

