
enum EESMTriggerInputSlot
{
    None,
    NATIVE_MAX = 0,
    Attack,
    SpecialAttack,
    SimpleSkill_1,
    SimpleSkill_2,
    SimpleSkill_3,
    UltraSkill = 10,
    DivineSkill,
    TemporarySkill,
    CustomSlot_0 = 20,
    CustomSlot_1,
    CustomSlot_2,
    CustomSlot_3,
    CustomSlot_4,
    CustomSlot_5,
    CustomSlot_6,
    CustomSlot_7,
    CustomSlot_8,
    CustomSlot_9,
    Item_1,
    Item_2,
    Item_3,
    Item_4,
    Sprint = 40,
    Jump,
    Crouch,
    Mount,
    CustomSlot_Sub = 50,
    CustomSlot_Equal,
    Interact_Area,
    Interact_Exit,
}

