

class UESMDeferredDeathCustomData : UESMCustomConfig_BP
{
    UPROPERTY()
    TArray<FName> StateNames;

    UESMDeferredDeathCustomData()
    {
        return;
    }
    UFUNCTION()
    bool CanComposite_Implementation() const
    {
        return true;
    }
    UFUNCTION()
    bool IsAutoGenerated_Implementation() const
    {
        return true;
    }
    UFUNCTION()
    void GenerateCompositedConfig_Implementation(const UESMCustomConfig TargetConfig, const TArray<UESMCustomConfig> &inout CompositeElement) const
    {
        UESMDeferredDeathCustomData local_22;
        UESMDeferredDeathCustomData local_4 = Cast<UESMDeferredDeathCustomData>(TargetConfig);
        for (auto local_20 : CompositeElement)
        {
            local_22 = Cast<UESMDeferredDeathCustomData>(local_20);
            if (local_22 == nullptr)
            {
                continue;
            }
            for (auto& local_36 : local_22.StateNames)
            {
                local_4.StateNames.AddUnique(local_36);
            }
        }
        return;
    }
}

namespace FDeferredDeathUtils
{
bool HasDeferredHitState(const FECSEntity &inout Entity)
{
    int local_6 = 0;
    if (!(local_6))
    {
        return false;
    }
    UESMDeferredDeathCustomData local_16 = (Cast<UESMDeferredDeathCustomData>(local_6.Asset.GetCustomConfig(UESMDeferredDeathCustomData)));
    return local_16 != nullptr && (local_16.StateNames.Num() > 0);
}
bool IsDeferredHitState(const FECSEntity &inout Entity, const FName &inout StateName)
{
    int local_8 = 0;
    if (StateName.IsNone())
    {
        return false;
    }
    if (!(local_8))
    {
        return false;
    }
    UESMDeferredDeathCustomData local_16 = (Cast<UESMDeferredDeathCustomData>(local_8.Asset.GetCustomConfig(UESMDeferredDeathCustomData)));
    if (local_16 == nullptr)
    {
        return false;
    }
    for (auto& local_30 : local_16.StateNames)
    {
        if (local_30.ToString().Contains(StateName.ToString(), ESearchCase(1), ESearchDir(0)))
        {
            return true;
        }
    }
    return false;
}
}
