

class UESMPreloadCustomData : UESMCustomConfig_BP
{
    UPROPERTY()
    TArray<TSoftObjectPtr<UAkAudioEvent>> PreloadEvents;
    UPROPERTY()
    TArray<TSoftObjectPtr<UAkStateValue>> PreloadStates;
    UPROPERTY()
    TArray<TSoftObjectPtr<UAkSwitchValue>> PreloadSwitches;
    UPROPERTY()
    TArray<TSoftObjectPtr<UAkRtpc>> PreloadRtpcs;
    UPROPERTY()
    TArray<TSoftClassPtr<AFXActor>> PreloadFXActors;

    UESMPreloadCustomData()
    {
        return;
    }
    UFUNCTION()
    bool CanComposite_Implementation() const
    {
        return true;
    }
    UFUNCTION()
    bool IsAutoGenerated_Implementation() const
    {
        return true;
    }
    UFUNCTION()
    void GenerateCompositedConfig_Implementation(const UESMCustomConfig TargetConfig, const TArray<UESMCustomConfig> &inout CompositeElement) const
    {
        UESMPreloadCustomData local_4 = Cast<UESMPreloadCustomData>(TargetConfig);
        for (auto local_20 : CompositeElement)
        {
            TArray<TSoftObjectPtr<UAkAudioEvent>> local_2 = Cast<UESMPreloadCustomData>(local_20);
            local_4.PreloadEvents.Append(local_2.PreloadEvents);
            local_2 = Cast<UESMPreloadCustomData>(local_20);
            local_4.PreloadSwitches.Append(local_2.PreloadSwitches);
            local_2 = Cast<UESMPreloadCustomData>(local_20);
            local_4.PreloadStates.Append(local_2.PreloadStates);
            local_2 = Cast<UESMPreloadCustomData>(local_20);
            local_4.PreloadRtpcs.Append(local_2.PreloadRtpcs);
            local_2 = Cast<UESMPreloadCustomData>(local_20);
            local_4.PreloadFXActors.Append(local_2.PreloadFXActors);
        }
        return;
    }
}

